### ISSUE TITLE
[Internal] Prep for Global Sprint

### ISSUE THREAD

**Issue by jeffreykeefer** [jeffreykeefer/Parkology#8]
- [ ] Parkology links readily accessible (Natalie)
- [ ] Create knowledge article (Natalie)
- [ ] Update issue log here (Jeffrey) (Natalie)
- [ ] Create new suggested issues for Global Sprint attendees (Natalie)
- [ ] Incident report specs in GitHub? (Natalie)
- [x] more copies of Mozilla Participation Guidelines (PDF) so we can print (Jeffrey) https://drive.google.com/drive/folders/1-iK24Mgm1UkfcdhGgQj5yZutwZEjh3SY
- [x] Create wifi name and password on print-out w/ TPL & Parkology logos (Natalie)
- [x] signage - TPL, Global Sprint (Jeffrey)
- [x] add welcome bot (Jeffrey)
- [x] power cords (Jeffrey)
- [x] hourly time slots in Ti.to (Natalie)
- [x] Refreshments (Natalie)
- [x] extend time slots in Ti.to (Natalie)
- [x] Figure out specs for Vidyo https://mozilla.github.io/global-sprint/site-hosts-guide/checklist/  (Natalie) update days and times on https://public.etherpad-mozilla.org/p/globalsprint-AV-testing-schedule 
- [x] additional laptop? (Natalie)
- [x] get interviewer questions (Natalie)
- [x] Swag from TPL? (Natalie)
- [x] Social Media Planning (with tags #MozSprint #Parkology #10MinWalk) (Natalie)
- [x] Assistance with help on Global Sprint day with John (Natalie)
- [x] Re-read How to be a Site Host (Jeffrey) (Natalie)
- [x] Request more swag (Jeffrey)
- [x] password specs for Ti.to (Jeffrey)
- [x] Swag from Mozilla? (Jeffrey)
- [x] wifi in the large conference room (Jeffrey)
- [x] Schedule check-in meetings between now and Global Sprint (Jeffrey)
- [x] Watch video on preparing for a site host (Jeffrey) (Natalie)
- [x] Watch recorded video from session on 4/18 (Jeffrey)
- [x] Discuss Global Sprint with Mary at Educational Video Center (Jeffrey)
#

**Comment by jurra** [comment]
Hi Jeffrey I read in the gitter you needed a logo, I quickly saw this when I read the name, and sketch this. If you like it I can give you the illustrator file, or other format that suits you best. Good luck!
![image](https://user-images.githubusercontent.com/18581201/39621224-45df1436-4f8e-11e8-8fc5-2a1a8bae29f9.png)

**Comment by jeffreykeefer** [comment]
@jurra Thank you so much for your kind contribution!! It is greatly appreciated!! We have a logo (though wish we would have seen your version first!!), and something affected it when it was uploaded but it has since been fixed. I really do appreciate your suggestions here!!

**Comment by jurra** [comment]
ok no problems it was really something I did for fun, and enjoyed :-)
